openapi: 3.0.3
info:
  title: TMF646 Gestión de Citas - Claro Ecuador
  description: >
    Esta API sigue el estándar TMF646 del TM Forum y se utiliza para gestionar citas y la 
    disponibilidad de slots para la atención de clientes asociados a la plataforma de Claro Ecuador. 
    Permite realizar la búsqueda de slots disponibles y actualizar las citas agendadas.
  version: 4.0.0
  x-specification-version: 4.0.0
  x-service-id: appointmentManagement
  x-release: 4.0.0
  x-documentation: https://example.com/docs/tmf646/v4
servers:
  - url: https://{api}:{port}/appointment/v4
paths:
  /searchTimeSlot:
    get:
      summary: Obtener slots de tiempo disponibles para agendamiento
      description: >
        En esta operación queremos obtener la información de los diferentes slots de tiempo 
        disponibles para el agendamiento de consultas de clientes. Se utilizarán los parámetros 
        de consulta para filtrar los resultados basados en fechas, categorías y otros criterios.
      operationId: getTimeSlots
      tags:
        - SearchTimeSlot
      security:
        - OAuth2: [read]
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
            example: "id,searchDate,availableTimeSlot"
        - name: resourceSpecification
          in: query
          required: true
          schema:
            type: string
            example: "technology"
        - name: requestedPeriod.startDateTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: "2024-12-01T10:00:00Z"
        - name: requestedPeriod.endDateTime
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: "2024-12-02T10:00:00Z"
        - name: relatedParty.role
          in: query
          required: true
          schema:
            type: string
            example: "originalChanel"
        - name: relatedParty.id
          in: query
          required: true
          schema:
            type: string
            example: "contratista"
        - name: appointmentType
          in: query
          required: true
          schema:
            type: string
            example: "activityType"
        - name: address.id
          in: query
          required: true
          schema:
            type: string
            example: "locationCode"
        - name: estimateTravelTime
          in: query
          required: true
          schema:
            type: string
            example: "true"
        - name: resourceCharacteristic
          in: query
          required: true
          schema:
            type: string
            example: "determinateCategory"
        - name: category
          in: query
          required: true
          schema:
            type: string
            example: "category"
        - name: actions
          in: query
          required: true
          schema:
            type: string
            example: "process"
        - name: Accept-Language
          in: header
          required: false
          description: "Indica el idioma preferido para la respuesta."
          schema:
            type: string
            example: "es"
        - name: If-NoneMatch
          in: header
          required: false
          description: "Se utiliza para la validación de caché, permitiendo al servidor saber si el recurso ha cambiado."
          schema:
            type: string
            example: "W/\"etag\""
        - name: X-External-Trx-Id
          in: header
          required: false
          description: "UUID de máximo 100 caracteres de tipo string."
          schema:
            type: string
            example: "external-transaction-id"
        - name: X-OriginChannel
          in: header
          required: false
          description: "Canal por el que proviene la petición. De tipo int."
          schema:
            type: integer
            example: 1
        - name: x-operation-id
          in: header
          required: false
          description: "De tipo string. Nombre de la operación que se va a realizar."
          schema:
            type: string
            example: "operation-id-123"
      responses:
        '200':
          description: Slots de tiempo disponibles encontrados exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchTimeSlotResponse'
        '400':
          description: Solicitud inválida. Parámetros incorrectos o faltantes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Acceso no autorizado. Token inválido o ausente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: No se encontraron slots de tiempo disponibles.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /appointment/{id}:
    patch:
      summary: Actualizar cita agendada
      description: >
        En esta operación se actualizará una cita previamente agendada. El ID especificado 
        en la URL se corresponde con el ID de la cita que se desea actualizar. 
        Se podrán modificar atributos como la fecha y hora, la descripción y otros detalles.
      operationId: updateAppointment
      tags:
        - Appointment
      security:
        - OAuth2: [write]
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador único de la cita a actualizar.
          schema:
            type: string
        - name: fields
          in: query
          required: false
          schema:
            type: string
            example: "id,description"
        - name: Accept-Language
          in: header
          required: false
          description: "Indica el idioma preferido para la respuesta."
          schema:
            type: string
            example: "es"
        - name: If-NoneMatch
          in: header
          required: false
          description: "Se utiliza para la validación de caché, permitiendo al servidor saber si el recurso ha cambiado."
          schema:
            type: string
            example: "W/\"etag\""
        - name: X-External-Trx-Id
          in: header
          required: false
          description: "UUID de máximo 100 caracteres de tipo string."
          schema:
            type: string
            example: "external-transaction-id"
        - name: X-OriginChannel
          in: header
          required: false
          description: "Canal por el que proviene la petición. De tipo int."
          schema:
            type: integer
            example: 1
        - name: x-operation-id
          in: header
          required: false
          description: "De tipo string. Nombre de la operación que se va a realizar."
          schema:
            type: string
            example: "operation-id-123"
      requestBody:
        description: Información para actualizar la cita agendada.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentUpdateRequest'
      responses:
        '200':
          description: Cita actualizada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '400':
          description: Solicitud inválida.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Acceso no autorizado. Token inválido o ausente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cita no encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: Autenticación OAuth 2.0 para acceder a la API.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            read: Permite acceso de lectura a los recursos.
            write: Permite acceso de escritura a los recursos.
  schemas:
    SearchTimeSlotResponse:
      type: object
      description: Respuesta para la búsqueda de slots de tiempo disponibles.
      properties:
        code:
          type: string
        status:
          type: string
        message:
          type: string
        transactionId:
          type: string
        timestamp:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              searchDate:
                type: string
              availableTimeSlot:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    validFor:
                      type: object
                      properties:
                        startDateTime:
                          type: string
                          format: date-time
                        endDateTime:
                          type: string
                          format: date-time
    AppointmentUpdateRequest:
      type: object
      description: Información para actualizar una cita.
      properties:
        startDateTime:
          type: string
        note:
          type: string
        description:
          type: string
        timeSlot:
          type: string
        resource:
          type: object
          properties:
            id:
              type: string
    AppointmentResponse:
      type: object
      description: Respuesta al actualizar una cita.
      properties:
        code:
          type: string
        status:
          type: string
        message:
          type: string
        transactionId:
          type: string
        timestamp:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        status:
          type: string
        transactionId:
          type: string
        timestamp:
          type: string
        message:
          type: string
        errorDetails:
          type: object
          properties:
            mensaje:
              type: string
            errorCode:
              type: string
